const form = document.getElementById("movie-form")
console.log(form)
const newMovie = docuemnt.getElementById("new-movie")
console.log(newMovie)
const container = document.getElementById("movie-container")
console.log(container)